# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rabdis < Formula
  desc "🐰 Rabdis – Play with redis keys from RabbitMQ messages"
  homepage "https://github.com/julienbreux/rabdis/"
  version "0.11.2"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/JulienBreux/rabdis/releases/download/v0.11.2/rabdis_0.11.2_Darwin_x86_64.tar.gz"
    sha256 "e3a59ee3119bac66b06d8df7d353121032f2178b958d09f3cc21354015a2c73b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/JulienBreux/rabdis/releases/download/v0.11.2/rabdis_0.11.2_Darwin_arm64.tar.gz"
    sha256 "9ce33174c7cfc8d04af2324dbced4153d2056ed6ce705e9bb712dbb0fcdbdbd6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/JulienBreux/rabdis/releases/download/v0.11.2/rabdis_0.11.2_Linux_x86_64.tar.gz"
    sha256 "362dba03701fa30dd559ff138c57bd5e82f369b3f9660b33c8a3e2e464ca73ee"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/JulienBreux/rabdis/releases/download/v0.11.2/rabdis_0.11.2_Linux_arm64.tar.gz"
    sha256 "2510fe59e490fc1cba4a95599f0a9f341f53cfe36b7d7bd1bf23f05dd2585d47"
  end

  def install
    bin.install "rabdis"
  end

  test do
    system "rabdis version"
  end
end
