# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rabdis < Formula
  desc "🐰 Rabdis – Play with redis keys from RabbitMQ messages"
  homepage "https://github.com/julienbreux/rabdis/"
  version "0.14.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JulienBreux/rabdis/releases/download/v0.14.0/rabdis_0.14.0_Darwin_x86_64.tar.gz"
      sha256 "f78d1cc2d7cac3d2fd979d9b6199fde2962d206e5658ba9dd9f0b09d6f3f5544"
    end
    if Hardware::CPU.arm?
      url "https://github.com/JulienBreux/rabdis/releases/download/v0.14.0/rabdis_0.14.0_Darwin_arm64.tar.gz"
      sha256 "4d2641e796807369c5395f599a49d7030c46a196e97c9b2f30f625a1f766ad88"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JulienBreux/rabdis/releases/download/v0.14.0/rabdis_0.14.0_Linux_x86_64.tar.gz"
      sha256 "47ebff350ffa339c7d89637095817e90edbb1ae73cf7e3470e8af65815cf09c9"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JulienBreux/rabdis/releases/download/v0.14.0/rabdis_0.14.0_Linux_arm64.tar.gz"
      sha256 "6fc1df2bbdd096761b980b156d8d86acc125c1d11252b12cb71a340d91de1a75"
    end
  end

  def install
    bin.install "rabdis"
  end

  test do
    system "rabdis version"
  end
end
