# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rabdis < Formula
  desc "🐰 Rabdis – Play with redis keys from RabbitMQ messages"
  homepage "https://github.com/julienbreux/rabdis/"
  version "0.14.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JulienBreux/rabdis/releases/download/v0.14.0/rabdis_0.14.0_Darwin_x86_64.tar.gz"
      sha256 "e0481709d36bc057097d0a7c9103d36d3c2c978646755af05ffcae0f9d44ef67"
    end
    if Hardware::CPU.arm?
      url "https://github.com/JulienBreux/rabdis/releases/download/v0.14.0/rabdis_0.14.0_Darwin_arm64.tar.gz"
      sha256 "947b77d8fca1d548ddabbed63b74268aaeefdd0e31747056ff68525775384aa0"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JulienBreux/rabdis/releases/download/v0.14.0/rabdis_0.14.0_Linux_x86_64.tar.gz"
      sha256 "b5cde00cc8374703a11179e0d915a85dbcb24fdb1da72b66b68cdb3972d7c695"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JulienBreux/rabdis/releases/download/v0.14.0/rabdis_0.14.0_Linux_arm64.tar.gz"
      sha256 "bec69ecabfa122c095519264260bd52f296fb311038474d6e4d91624af5b1620"
    end
  end

  def install
    bin.install "rabdis"
  end

  test do
    system "rabdis version"
  end
end
